const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

const RESPONSE_CODES = {
  SUCCESS: 'SUCCESS',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CODE_ERROR: 'CODE_ERROR',
  NO_DATA: 'NO_DATA',
  RECORD_EXISTS: 'RECORD_EXISTS',
  DUPLICATE_DATA: 'DUPLICATE_DATA',
  INSERT_FAILED: 'INSERT_FAILED',
  UPDATE_FAILED: 'UPDATE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
};

module.exports = {
  STATUS_CODES,
  RESPONSE_CODES,
};
